# Site settings
title: The McComb Foundation
email: 
description: "This is a description" # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "mccombfoundation.org" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
